import { Inter } from "next/font/google";
import "./globals.css";
import { Roman } from "./font";

const roman= Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roman.className} m-2`}>{children}</body>
    </html>
  );
}
